### ISSUE TITLE
Drop-in replacement of jop-io/kontonummer.js

### ISSUE THREAD

**Issue by ariselseng** [swantzter/kontonummer#31]
Hi,
Thank you for this project.
It would be nice to be able to get a single file drop in replacement for kontonummer.js
I am not very familiar with your tooling, but maybe it is not that hard to achieve?

**Comment by swantzter** [comment]
Hi,

I'd assume it'd look something like this:

```ts
function kontonummer (number: string) {
  try {
    const k = new Kontonummer(number)
    return {
      bank_name: k.bankName,
      clearing_number: k.sortingCode, 
      account_number: k.accountNumber
    }
  } catch {
    return false
  }
}
```

However I'm not sure if it's right to place it in this library, or if it's better to add that snippet to your own codebase to simplify migration

**Comment by ariselseng** [comment]
Thanks. In my project there is no npm/yarn. We are primarily a backend service with some very simple html forms.
If I could choose, I would want a simple js file I could include.

**Comment by swantzter** [comment]
Fair, I'll havw to test this when I have a computer at hand, but I think you could do something like

```html
<script type="module">
import Kontonummer from 'https://cdn.jsdelivr.net/npm/kontonummer@4.0.0/dist/esm/index.min.js'

function kontonummer (number) {
  try {
    const k = new Kontonummer(number)
    return {
      bank_name: k.bankName,
      clearing_number: k.sortingCode, 
      account_number: k.accountNumber
    }
  } catch {
    return false
  }
}
</script>
```

**Comment by ariselseng** [comment]
Thank you so much for following up on this. The example is a great start, but I am afraid the dependencies 
When it is importing the other files it cannot find them due to the missing extension in the url:
![image](https://github.com/swantzter/kontonummer/assets/445843/a3c12785-59aa-4b7a-b816-7b56b9b2454c)
I tried building from source manually and add ".js" on all the imports and then it worked.

**Comment by swantzter** [comment]
Yeah I was afraid that would happen. I'll see if I can add that to make sure it works when imported in browsers, and push out a new patch version

**Comment by swantzter** [comment]
All right, 4.0.1 should do the trick, I've also added the above snippet as an example to the [release notes](https://github.com/swantzter/kontonummer/releases/tag/v4.0.1)

**Comment by ariselseng** [comment]
Thanks, it works!
To actually get kontonumber function available in my code I needed to add it to window:

 <script type="module">
        import Kontonummer from 'https://cdn.jsdelivr.net/npm/kontonummer@4.0.1/dist/esm/index.min.js'

        window.kontonummer = function (number) {
            try {
                const k = new Kontonummer(number)
                return {
                    bank_name: k.bankName,
                    clearing_number: k.sortingCode,
                    account_number: k.accountNumber
                }
            } catch {
                return false
            }
        }
    </script>
